#!/bin/bash

echo "Downloading previous ccache . . . . . ."

cd /tmp
curl https://www.hisyam99.workers.dev/ccache-fluid-1-4-fix-2.tar.gz -o ccache.tar.gz
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz
